spring:
  config:
    activate:
      on-profile: production
  application:
    name: employees
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  thymeleaf:
    cache: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
  web:
    resources:
      add-mappings: true
      static-locations: classpath:/static/
  mvc:
    static-path-pattern: /**

server:
  port: 8080
